# Application Properties for API Server
spring.application.name=yinkcore-api   

spring.profiles.active=dev

# security configuration
spring.security.user.name=dev
spring.security.user.password=12345
spring.security.jwt.secret-key=my-super-secret-key-my-super-secret-key
spring.security.jwt.access-token-expiration=900000
spring.security.jwt.refresh-token-expiration=604800000

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/starter_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
       
# JPA configuration
# spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: validate
# spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql: true
spring.jpa.open-in-view: false

# server port
server.port: 8000
            
# Author Information
app.author.name=Young Lecturer
app.author.email=YoungLecturer7@gmail.com

# logging level
logging.level.[org.flywaydb]=DEBUG